/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-08-23 17:20:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.personas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class tbpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "template_superior.jsp", out, false);
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<h2>Ejemplo TB....</h2>\r\n");
      out.write("<h2>Titulo 2 </h2>\r\n");
      out.write("<form method=\"post\" action=\"");
      out.print(request.getContextPath());
      out.write("/altaPersonas\">\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"nombre\">Nombre</label>\r\n");
      out.write("    <input type=\"text\" class=\"form-control\" name=\"nombre\" id=\"nombre\" placeholder=\"Nombre\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"apellido\">Apellido</label>\r\n");
      out.write("    <input type=\"text\" class=\"form-control\" name=\"apellido\" id=\"apellido\" placeholder=\"Apellido\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"email\">Email address</label>\r\n");
      out.write("    <input type=\"email\" class=\"form-control\" name=\"email\" id=\"email\" placeholder=\"Email\">\r\n");
      out.write("  </div>\r\n");
      out.write(" <div class=\"form-group\">\r\n");
      out.write("    <label for=\"sexo\">Sexo:</label>  \r\n");
      out.write("\t<label class=\"radio-inline\">\r\n");
      out.write("\t  <input type=\"radio\" name=\"optionSexo\" id=\"fem\" value=\"f\"> F\r\n");
      out.write("\t</label>\r\n");
      out.write("\t<label class=\"radio-inline\">\r\n");
      out.write("\t <input type=\"radio\" name=\"optionSexo\" id=\"masc\" value=\"m\"> M\r\n");
      out.write("\t</label>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("    <label for=\"localidad\">Localidad:</label>\r\n");
      out.write("\t <select class=\"form-control\" name=\"localidad\" >\r\n");
      out.write("\t  <option>1</option>\r\n");
      out.write("\t  <option>2</option>\r\n");
      out.write("\t  <option>3</option>\r\n");
      out.write("\t  <option>4</option>\r\n");
      out.write("\t  <option>5</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("    <label for=\"notas\">Notas</label>\r\n");
      out.write("   <textarea name=\"notas\" id=\"notas\" class=\"form-control\" rows=\"3\"></textarea>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("  <div class=\"checkbox\">\r\n");
      out.write("    <label>\r\n");
      out.write("      <input type=\"checkbox\" id=\"esCasado\" name=\"esCasado\"> Es Casado\r\n");
      out.write("    </label>\r\n");
      out.write("  </div>\r\n");
      out.write(" </div>\r\n");
      out.write("  <button type=\"submit\" class=\"btn btn-default\">Submit</button>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "template_inferior.jsp", out, false);
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
